(define (domain house-exploration)
    (:requirements :strips :typing)
    (:types location direction)
    (:predicates
        (at ?loc - location)
        (door-closed ?loc1 - location ?loc2 - location ?dir - direction)
        (door-open ?loc1 - location ?loc2 - location ?dir - direction)
        (connected ?loc1 - location ?loc2 - location ?dir - direction)
    )
    (:action open-door
        :parameters (?loc1 - location ?loc2 - location ?dir - direction)
        :precondition (and (at ?loc1) (door-closed ?loc1 ?loc2 ?dir))
        :effect (and (door-open ?loc1 ?loc2 ?dir) (not (door-closed ?loc1 ?loc2 ?dir)))
    )
    (:action move
        :parameters (?from - location ?to - location ?dir - direction)
        :precondition (and (at ?from) (door-open ?from ?to ?dir) (connected ?from ?to ?dir))
        :effect (and (at ?to) (not (at ?from)))
    )
)