(define (domain exploration) 
(:requirements :strips :typing) 
(:types location direction) 
(:action open-door :parameters (?loc1 - location ?loc2 - location ?dir - direction) :preconditions (and (at ?loc1) (door-closed ?loc1 ?loc2 ?dir)) :effects (door-open ?loc1 ?loc2 ?dir)) 
(:action move :parameters (?from - location ?to - location ?dir - direction) :preconditions (and (at ?from) (door-open ?from ?to ?dir)) :effects (at ?to)))